package runtime

import (
	"fmt"
	"slices"
)

// webServers lists the catalogue keys usable as a project web server, default first.
var webServers = []string{"caddy", "apache", "nginx"}

// DefaultWebServer is the web server used when a request does not name one.
const DefaultWebServer = "caddy"

// IsWebServer reports whether variant is a supported project web server.
func IsWebServer(variant string) bool {
	return slices.Contains(webServers, variant)
}

// WebConfig is the generated configuration file of a project web server.
type WebConfig struct {
	FileName string // file name below the project's web config directory
	Target   string // bind-mount target inside the web container
	Content  string
}

// WebOptions selects the branch of a rendered web-server configuration.
type WebOptions struct {
	// PHP forwards PHP requests to the PHP-FPM container ("php:9000" on the project network)
	// with the front controller (index.php) handling unknown paths.
	PHP bool
	// SPAFallback answers unknown paths with /index.html so client-side routers survive a
	// reload. Only meaningful without PHP.
	SPAFallback bool
}

// WebServiceConfig is the persisted configuration of a project's web service.
type WebServiceConfig struct {
	SPAFallback bool `json:"spaFallback,omitempty"`
}

// WebServerConfig renders the configuration of the given web server variant. All variants
// serve static files from the document root. With PHP, requests for .php files (and, via
// the front controller, unknown paths) go to PHP-FPM; without PHP the document root is
// served as is, dot paths (/.env, /.git/…, /.next/…) are denied and unknown paths return
// 404 or, with the SPA fallback, /index.html.
func WebServerConfig(variant, docroot string, o WebOptions) (WebConfig, error) {
	switch variant {
	case "caddy":
		return WebConfig{FileName: "Caddyfile", Target: "/etc/caddy/Caddyfile", Content: caddyfile(docroot, o)}, nil
	case "apache":
		return WebConfig{FileName: "httpd.conf", Target: "/usr/local/apache2/conf/httpd.conf", Content: httpdConf(docroot, o)}, nil
	case "nginx":
		return WebConfig{FileName: "default.conf", Target: "/etc/nginx/conf.d/default.conf", Content: nginxConf(docroot, o)}, nil
	}
	return WebConfig{}, fmt.Errorf("unsupported web server %q", variant)
}

func webRoot(docroot string) string {
	root := "/var/www/html"
	if docroot != "" {
		root = root + "/" + docroot
	}
	return root
}

const generatedHeader = "# Generated by Envoryx - do not edit, changes are overwritten.\n"

// uploadDirs matches the directories, seen from the document root, where PHP applications
// keep user uploads and generated files: WordPress (wp-content/uploads, Bedrock's
// app/uploads), Drupal (sites/*/files), TYPO3 (fileadmin, typo3temp), Shopware and
// Magento (media, thumbnail), Laravel (the public/storage link) and the common uploads/.
// The CMS names match anywhere so installs in a subdirectory are covered; the generic
// names only at the document root. A PHP file that lands there through an upload form
// would otherwise run like application code. The CMSs ship .htaccess rules for this,
// which only Apache reads, so all three servers get the rule themselves, as in the
// hardening recipes of Drupal, WordPress and Magento for nginx. Only requests for .php
// files (and their path info) are refused: everything else, such as Drupal's image
// styles, which are generated through index.php, still goes its usual way.
const uploadDirs = `(?:/wp-content/uploads|/app/uploads|/sites/[^/]+/files|/fileadmin|/typo3temp|^/(?:uploads|media|thumbnail|storage))/`

// uploadPHP matches a PHP script below one of the uploadDirs.
const uploadPHP = `(?i)` + uploadDirs + `.*\.php(?:/|$)`

// Caddyfile renders the Caddy configuration.
func Caddyfile(docroot string, php bool) string { return caddyfile(docroot, WebOptions{PHP: php}) }

func caddyfile(docroot string, o WebOptions) string {
	// Caddy's file_server has no dotfile deny of its own: dotfiles (.env, .git, .htaccess)
	// get a 404 like on nginx and Apache, .well-known stays reachable. try_files runs before
	// respond, so an existing dotfile keeps its path and is still refused.
	handlers := "\t@dot {\n\t\tpath_regexp (^|/)\\.\n\t\tnot path /.well-known/*\n\t}\n\trespond @dot 404\n"
	if o.PHP {
		handlers += caddyPHP
	} else if o.SPAFallback {
		handlers += "\ttry_files {path} /index.html\n"
	}
	// The project is reached through Envoryx's proxy from a private address; trusting it
	// keeps its X-Forwarded-Proto and X-Forwarded-For for the application (and Xdebug).
	return generatedHeader + fmt.Sprintf(`{
	admin off
	auto_https off
	servers {
		trusted_proxies static private_ranges
	}
}

:80 {
	root * %s
	encode gzip
%s	file_server
	log {
		output stdout
		format console
	}
}
`, webRoot(docroot), handlers)
}

// caddyPHP hands PHP requests to PHP-FPM. php_fastcgi sets HTTPS only for TLS on Caddy's
// own listener, but TLS ends at Envoryx's proxy, so a request that came in over https
// would look like http to PHP: Laravel, Symfony, Shopware and TYPO3 then build http://
// links and redirects unless they are told to trust proxies. Requests the proxy marks
// as https get HTTPS=on, REQUEST_SCHEME=https and the port the browser used (443 when
// the Host header carries none), as if PHP sat right behind the TLS endpoint. Plain http
// keeps Caddy's own values, with HTTPS unset rather than empty, since some apps only
// check isset($_SERVER['HTTPS']).
//
// PHP below the uploadDirs is refused. A directory there that holds an index.php is
// refused as well, since php_fastcgi would run that file for the directory's URL; nginx
// and Apache reach it through an internal redirect that their rule already covers.
const caddyPHP = `	@uploadphp path_regexp ` + uploadPHP + `
	respond @uploadphp 403
	@uploadindex {
		path_regexp (?i)` + uploadDirs + `(?:.*/)?$
		file {path}index.php
	}
	respond @uploadindex 403
	@https header X-Forwarded-Proto https
	map {http.request.port} {envoryx_https_port} {
		~^(\d+)$ ${1}
		default 443
	}
	php_fastcgi @https php:9000 {
		env HTTPS on
		env REQUEST_SCHEME https
		env SERVER_PORT {envoryx_https_port}
	}
	php_fastcgi php:9000
`

// NginxConf renders the nginx server block. The stock nginx.conf of the official image
// includes conf.d/*.conf, so only the server block is generated.
func NginxConf(docroot string, php bool) string { return nginxConf(docroot, WebOptions{PHP: php}) }

func nginxConf(docroot string, o WebOptions) string {
	fallback := "=404"
	index := "index.html"
	fastcgi, maps := "", ""
	if o.SPAFallback && !o.PHP {
		fallback = "/index.html"
	}
	if o.PHP {
		fallback = "/index.php?$query_string"
		index = "index.php index.html"
		// The read timeout is generous so requests paused in the debugger are not cut off.
		// nginx takes the first regex location that matches, so the upload rule comes
		// before the PHP one.
		fastcgi = `
	location ~ "` + uploadPHP + `" {
		deny all;
	}

	location ~ \.php$ {
		try_files $uri =404;
		fastcgi_pass php:9000;
		fastcgi_index index.php;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
		fastcgi_param HTTPS $envoryx_https if_not_empty;
		fastcgi_param REQUEST_SCHEME $envoryx_scheme;
		fastcgi_param SERVER_PORT $envoryx_port;
		fastcgi_read_timeout 3600;
	}
`
		maps = nginxPHPMaps
	}
	return generatedHeader + maps + fmt.Sprintf(`server {
	listen 80;
	server_name _;
	root %s;
	index %s;

	client_max_body_size 0;
	gzip on;
	gzip_types text/plain text/css text/xml application/json application/javascript application/xml image/svg+xml;

	access_log /dev/stdout;
	error_log /dev/stderr;

	location / {
		try_files $uri $uri/ %s;
	}
%s
	location ~ /\.(?!well-known) {
		deny all;
	}
}
`, webRoot(docroot), index, fallback, fastcgi)
}

// nginxPHPMaps derive what PHP is told about the request from the proxy's
// X-Forwarded-Proto, for the reason given at caddyPHP. The fastcgi_param lines using
// them come after fastcgi_params, and PHP-FPM keeps the last value of a repeated param.
// Plain http keeps nginx's own values.
const nginxPHPMaps = `map $http_x_forwarded_proto $envoryx_https {
	https on;
	default $https;
}
map $http_x_forwarded_proto $envoryx_scheme {
	https https;
	default $scheme;
}
map "$http_x_forwarded_proto:$http_host" $envoryx_port {
	"~^https:.*:([0-9]+)$" $1;
	"~^https:" 443;
	default $server_port;
}

`

// HTTPDConf renders a complete httpd.conf for the official httpd image. The stock file
// ships with mod_rewrite and mod_proxy_fcgi disabled, so it is replaced rather than
// extended. AllowOverride All enables .htaccess files as on a typical shared host.
func HTTPDConf(docroot string, php bool) string { return httpdConf(docroot, WebOptions{PHP: php}) }

func httpdConf(docroot string, o WebOptions) string {
	index := "index.html"
	fastcgi := ""
	// The PHP branch keeps Apache's stock .ht* rule; the static branch denies every dot
	// path since no front controller stands in front of the document root. FilesMatch
	// only sees the final path component (/.env), so dot-directories (/.git/config,
	// /.next/…) need DirectoryMatch as well - that is what Caddy's (^|/)\. and nginx's
	// location ~ /\. already cover.
	access := `<Files ".ht*">
	Require all denied
</Files>`
	if !o.PHP {
		access = `<FilesMatch "^\.">
	Require all denied
</FilesMatch>
<DirectoryMatch "/\.">
	Require all denied
</DirectoryMatch>`
		if o.SPAFallback {
			fastcgi = "\nFallbackResource /index.html\n"
		}
	}
	if o.PHP {
		index = "index.php index.html"
		// For the reason given at caddyPHP. Apache already takes SERVER_PORT from the Host
		// header, so it only needs fixing when the header carries no port. Location sections
		// are merged after Directory and .htaccess, so no .htaccess can lift the upload rule.
		fastcgi = `
<FilesMatch "\.php$">
	SetHandler "proxy:fcgi://php:9000"
</FilesMatch>
<LocationMatch "` + uploadPHP + `">
	Require all denied
</LocationMatch>
ProxyFCGISetEnvIf "%{HTTP:X-Forwarded-Proto} == 'https'" HTTPS on
ProxyFCGISetEnvIf "%{HTTP:X-Forwarded-Proto} == 'https'" REQUEST_SCHEME https
ProxyFCGISetEnvIf "%{HTTP:X-Forwarded-Proto} == 'https' && ! %{HTTP_HOST} =~ /:[0-9]+$/" SERVER_PORT 443
# Generous so requests paused in the debugger are not cut off.
ProxyTimeout 3600
`
	}
	root := webRoot(docroot)
	return generatedHeader + fmt.Sprintf(`ServerRoot "/usr/local/apache2"
Listen 80
ServerName localhost
ServerTokens Prod

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authn_file_module modules/mod_authn_file.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
LoadModule authz_user_module modules/mod_authz_user.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule auth_basic_module modules/mod_auth_basic.so
LoadModule reqtimeout_module modules/mod_reqtimeout.so
LoadModule filter_module modules/mod_filter.so
LoadModule deflate_module modules/mod_deflate.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule env_module modules/mod_env.so
LoadModule expires_module modules/mod_expires.so
LoadModule headers_module modules/mod_headers.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule dir_module modules/mod_dir.so
LoadModule alias_module modules/mod_alias.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_fcgi_module modules/mod_proxy_fcgi.so

User daemon
Group daemon

ErrorLog /proc/self/fd/2
LogLevel warn
LogFormat "%%h %%l %%u %%t \"%%r\" %%>s %%b" common
CustomLog /proc/self/fd/1 common

TypesConfig conf/mime.types
AddOutputFilterByType DEFLATE text/html text/plain text/css text/xml application/json application/javascript application/xml image/svg+xml

<Directory />
	AllowOverride None
	Require all denied
</Directory>

DocumentRoot "%s"
<Directory "%s">
	Options FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>

%s

DirectoryIndex %s
%s`, root, root, access, index, fastcgi)
}
