ALTER TABLE projects ADD COLUMN git_url TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN git_branch TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN git_username TEXT NOT NULL DEFAULT '';
ALTER TABLE projects ADD COLUMN git_token TEXT NOT NULL DEFAULT '';
